name: .NET Console App CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-publish:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: repos/Console_Emoticon_Support/Console_Emoticon_Support.sln
      Project_Path: Console_Emoticon_Support/Console_Emoticon_Support.csproj

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Install dotnet-format tool
      run: dotnet tool install -g dotnet-format

    - name: Check code formatting
      run: dotnet format $env:Solution_Name --verify-no-changes
      continue-on-error: false

    - name: Build
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}

    - name: Run tests
      run: dotnet test $env:Solution_Name --configuration ${{ matrix.configuration }}

    - name: Publish
      run: dotnet publish $env:Project_Path --configuration ${{ matrix.configuration }} --output ./publish

    - name: Upload published files
      uses: actions/upload-artifact@v4
      with:
        name: PublishedApp-${{ matrix.configuration }}
        path: ./publish
